# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField(null=True)),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=255)),
                ('annee_ECN', models.CharField(help_text='Ann\xe9e concours ECN', max_length=255)),
                ('semestre', models.CharField(help_text='Quel semestre avez-vous commenc\xe9 en novembre', max_length=255)),
                ('annee_debut_post_internat', models.CharField(help_text='Ann\xe9e (pr\xe9visible ou effective) de d\xe9but de post-internat', max_length=255)),
                ('inter_region', models.CharField(help_text='Votre inter-r\xe9gion de formation (DOM-TOM, Est, Ile de France, Nord, Ouest, Rh\xf4ne-Alpes, Sud, Sud-Ouest) ?', max_length=255)),
                ('service_actuel', models.CharField(help_text='Votre service actuel : pr\xe9cisez votre centre, le service, le chef de service et la ville', max_length=255)),
                ('diplome_master_2', models.CharField(choices=[('non', 'non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name='Master 2')),
                ('diplome_DESC_andrologie', models.CharField(choices=[('non', 'non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name="DESC d'andrologie")),
                ('diplome_DESC_oncologie', models.CharField(choices=[('non', 'non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name="DESC d'oncologie")),
                ('diplome_autre', models.CharField(blank=True, default='', help_text='Si oui, pr\xe9cisez.', max_length=255, null=True, verbose_name='Autres diplomes')),
                ('statut_actuel', models.CharField(choices=[('interne DES', 'interne DES'), ('interne titre \xe9tranger', 'interne titre \xe9tranger'), ('assistant', 'assistant'), ('CCA', 'CCA'), ('autre', 'autre')], max_length=255, null=True)),
                ('statut_autre', models.CharField(blank=True, choices=[('interne DES', 'interne DES'), ('interne titre \xe9tranger', 'interne titre \xe9tranger'), ('assistant', 'assistant'), ('CCA', 'CCA'), ('autre', 'autre')], help_text="Pr\xe9cisez, si autre statut (m\xe9daille d'or, ann\xe9e de c\xe9sure, mobilit\xe9 ...)", max_length=255, null=True)),
                ('justificatif_scolarite', models.FileField(upload_to='test/')),
                ('choix_adhesion', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
