# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERMGMT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='adresse compl\xe8te'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='annee_ECN',
            field=models.CharField(help_text='Ann\xe9e du concours ECN', max_length=255, verbose_name='ann\xe9e ECN'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='annee_debut_post_internat',
            field=models.CharField(help_text='Ann\xe9e, pr\xe9visible ou effective, de d\xe9but de post-internat', max_length=255, verbose_name='ann\xe9e du d\xe9but de post-internat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_naissance',
            field=models.DateField(null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diplome_autre',
            field=models.TextField(blank=True, default='', help_text='Si oui, pr\xe9cisez.', null=True, verbose_name='Autres diplomes'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inter_region',
            field=models.CharField(choices=[('Ile de France', 'Ile de France'), ('Est', 'Est'), ('Nord', 'Nord'), ('Ouest', 'Ouest'), ('Rh\xf4ne-Alpes', 'Rh\xf4ne-Alpes'), ('Sud', 'Sud'), ('Sud-Ouest', 'Sud-Ouest'), ('DOM-TOM', 'DOM-TOM')], max_length=255, verbose_name='inter-r\xe9gion de formation'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='justificatif_scolarite',
            field=models.FileField(upload_to='uploads/justificatifs/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semestre',
            field=models.CharField(help_text='Quel semestre avez-vous commenc\xe9 en novembre', max_length=255, verbose_name='semestre commenc\xe9'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service_actuel',
            field=models.CharField(help_text='Pr\xe9cisez votre centre, le service, le chef de service et la ville', max_length=255, verbose_name='votre service actuel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statut_autre',
            field=models.CharField(blank=True, help_text="Pr\xe9cisez, si autre statut (m\xe9daille d'or, ann\xe9e de c\xe9sure, mobilit\xe9 ...)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(max_length=255, verbose_name='t\xe9l\xe9phone'),
        ),
    ]
