# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERMGMT', '0002_auto_20161214_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='diplome_DESC_oncologie',
        ),
        migrations.AddField(
            model_name='profile',
            name='diplome_DESC_oncologie_1',
            field=models.CharField(choices=[('Non', 'Non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name="DESC d'oncologie option m\xe9dicale"),
        ),
        migrations.AddField(
            model_name='profile',
            name='diplome_DESC_oncologie_2',
            field=models.CharField(choices=[('Non', 'Non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name="DESC d'oncologie option chirurgicale"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='adresse postale compl\xe8te'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='annee_ECN',
            field=models.CharField(max_length=255, verbose_name="Ann\xe9e du concours de l'ECN"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diplome_DESC_andrologie',
            field=models.CharField(choices=[('Non', 'Non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name="DESC d'andrologie"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diplome_master_2',
            field=models.CharField(choices=[('Non', 'Non'), ('Pas int\xe9ress\xe9', 'Pas int\xe9ress\xe9'), ('En cours', 'En cours'), ('Valid\xe9', 'Valid\xe9')], default='', max_length=255, null=True, verbose_name='Master 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='justificatif_scolarite',
            field=models.FileField(help_text='Certificat de scolarit\xe9 (si interne), feuille de paie (si CCA) ou attestation du chef de service', upload_to='uploads/justificatifs/', verbose_name='Pi\xe8ce justificative'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semestre',
            field=models.CharField(max_length=255, verbose_name='semestre commenc\xe9 en novembre 2016'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statut_actuel',
            field=models.CharField(choices=[('Interne DES', 'Interne DES'), ('Interne titre \xe9tranger', 'Interne titre \xe9tranger'), ('Assistant', 'Assistant'), ('CCA', 'CCA'), ('Autre', 'Autre')], max_length=255, null=True),
        ),
    ]
