# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERMGMT', '0003_auto_20161214_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='statut_autre',
            field=models.CharField(blank=True, help_text="Pr\xe9cisez, si autre statut (m\xe9daille d'or, ann\xe9e de c\xe9sure, mobilit\xe9, ann\xe9e recherche ...)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
